In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('covid_toy.csv')
df.shape

(100, 6)

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [11]:
df['fever'].value_counts()

fever
101.0    17
98.0     17
104.0    14
100.0    13
99.0     10
102.0    10
103.0     9
Name: count, dtype: int64

In [8]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['has_covid']),
                                                       df['has_covid'],test_size=0.2)

In [ ]:
#adding simple imputer to fever class
si = SimpleImputer(strategy='most_frequent')

x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.fit_transform(x_test[['fever']])

In [32]:
x_train_fever.shape

(80, 1)

In [78]:
# ordinal_encoding -> cough

oe = OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough = oe.fit_transform(x_train[['cough']])

x_test_cough = oe.transform(x_test[['cough']])

In [80]:
x_train.head()

    age  gender  fever   cough       city
82   24    Male   98.0    Mild    Kolkata
5    84  Female    NaN    Mild  Bangalore
51   11  Female  100.0  Strong    Kolkata
56   71    Male    NaN  Strong    Kolkata
90   59  Female   99.0  Strong      Delhi

In [64]:
#OneHotEncoder --> gender , city
oe = OneHotEncoder(drop='first',sparse_output=False)

x_train_gender_city = oe.fit_transform(x_train[['gender','city']])

x_test_gender_city = oe.fit_transform(x_test[['gender','city']])

In [66]:
x_train_gender_city.shape

(80, 4)

In [68]:
x_train.head(2)

    age  gender  fever cough       city
82   24    Male   98.0  Mild    Kolkata
5    84  Female    NaN  Mild  Bangalore

In [75]:
#Extracting age column
x_train_age = x_train.drop(columns=['gender','fever','cough','city'])

x_test_age = x_test.drop(columns=['gender','fever','cough','city'])

In [95]:
#concatination
x_trian_transformed = np.concatenate((x_train_age,x_train_cough,x_train_fever,x_train_gender_city),axis=1)

x_test_transformed = np.concatenate((x_test_age,x_test_cough,x_test_fever,x_test_gender_city),axis=1)

In [97]:
x_trian_transformed.shape
x_test_transformed.shape

(20, 7)

In [99]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [100]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [98]:
from sklearn.compose import ColumnTransformer

In [108]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(strategy='mean'),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],
remainder='passthrough'
)

In [109]:
transformer.fit_transform(x_train).shape

(80, 7)

In [107]:
transformer.transform(x_test).shape

(20, 7)