In [2]:
import numpy as np
import pandas as pd 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [5]:
df = pd.DataFrame({
    'Product_Code': [
        '2c',
        '3a',
        '5b',
        '123xy',
        '2a5b',
        np.nan,
        '7z',
        '10ab',
        '4x',
        '99yz',
        np.nan,
        '15m',
        '8n',
        '200pq',
        '6k'
    ]
})
df

   Product_Code
0            2c
1            3a
2            5b
3         123xy
4          2a5b
5           NaN
6            7z
7          10ab
8            4x
9          99yz
10          NaN
11          15m
12           8n
13        200pq
14           6k

In [9]:
#filling the missing values
si = SimpleImputer(strategy='most_frequent')
df[['Product_Code']] = si.fit_transform(df[['Product_Code']])

In [13]:
#extracting alphabetics
df['Number'] = pd.to_numeric(
    df['Product_Code'].str.extract(r'(\d+)')[0],
    errors='coerce'
)

df['Letters'] = df['Product_Code'].str.extract(r'([A-Za-z]+)')

In [14]:
df

   Product_Code  Number Letters
0            2c       2       c
1            3a       3       a
2            5b       5       b
3         123xy     123      xy
4          2a5b       2       a
5          10ab      10      ab
6            7z       7       z
7          10ab      10      ab
8            4x       4       x
9          99yz      99      yz
10         10ab      10      ab
11          15m      15       m
12           8n       8       n
13        200pq     200      pq
14           6k       6       k