In [ ]:
#One hot encoding

In [46]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('cars.csv')
df.shape

(8128, 5)

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [80]:
df['brand'].nunique()

32

In [21]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [23]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

OneHotEncoding using pandas

In [25]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [26]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

OneHotEncoding using sklearn

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [51]:
x_train , x_test , y_train , y_test = train_test_split(df.drop('selling_price' , axis = 1),df['selling_price'],
                                                       test_size=0.2,random_state=0)

In [13]:
y_test.shape

(1626,)

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [52]:
oh = OneHotEncoder(drop='first')

In [54]:
x_train_encoded = oh.fit_transform(x_train[['fuel','owner']]).toarray()
x_test_encoded = oh.transform(x_test[['fuel','owner']]).toarray()

In [55]:
x_train_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(6502, 7))

In [56]:
x_test_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]], shape=(1626, 7))

In [31]:
x_train.head()

         brand  km_driven    fuel         owner
3042   Hyundai      60000     LPG   First Owner
1520      Tata     150000  Diesel   Third Owner
2611   Hyundai     110000  Diesel  Second Owner
3544  Mahindra      28000  Diesel  Second Owner
4138    Maruti      15000  Petrol   First Owner

In [59]:
new_df = np.hstack((x_train[['brand','km_driven']].values,x_train_encoded))

In [61]:
pd.DataFrame(new_df).sample(10)

              0       1    2    3    4    5    6    7    8
6376       Tata   80000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
656        Tata  120000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4813    Hyundai   40000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
793    Mahindra   58000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1088     Maruti  120000  0.0  0.0  1.0  0.0  1.0  0.0  0.0
1803    Hyundai   50000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
5612  Chevrolet   37000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
129     Hyundai   56000  0.0  0.0  1.0  0.0  0.0  0.0  1.0
5347     Maruti    5621  0.0  0.0  1.0  0.0  0.0  0.0  0.0
5101     Toyota   27000  1.0  0.0  0.0  0.0  0.0  0.0  0.0

df['brand'] feature encoding

In [67]:
counts = df['brand'].value_counts()

In [69]:
df['brand'].nunique()
threshold = 100

In [ ]:
repl = counts[counts <= threshold].index

In [77]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2899,False,False,False,False,False,False,True,False,False,False,False,False,False
1039,False,False,False,False,False,False,False,False,False,False,True,False,False
5338,False,False,False,False,False,False,True,False,False,False,False,False,False
1596,False,False,False,False,False,False,True,False,False,False,False,False,False
2505,False,False,False,False,False,False,True,False,False,False,False,False,False
948,False,False,False,False,False,False,False,False,False,True,False,False,False
274,False,False,False,False,False,False,False,False,False,False,False,False,True
598,False,False,False,True,False,False,False,False,False,False,False,False,False
6436,False,False,False,False,False,False,True,False,False,False,False,False,False
592,False,False,False,False,True,False,False,False,False,False,False,False,False